### ISSUE TITLE
Document the process for creating new Quay.io repositories

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/redhat-cop.github.io#13]
Now that we have automation in the org repo, we should have a document that covers that process.

**Comment by etsauer** [comment]
We should also put something in the org repo readme that explains what types of things are managed in the repo.

**Comment by garethahealy** [comment]
@etsauer ; think the docs have already been done by @pabrahamsson 
- https://github.com/redhat-cop/redhat-cop.github.io/pull/12
