### ISSUE TITLE
Feature/Logo - Red Hat Community of Practice (CoP)

### ISSUE THREAD

**Issue by GrooveCS** [redhat-cop/redhat-cop.github.io#19]
# New Logo  -  Red Hat Community of Practice (CoP)

Propose the following:

1. Connect with Red Hat Global CoP community for the suggestion, proposals, and feedback for a logo 
1. Who is available to run point on this challenge
1.  Which communities should be included in this discussion
  - [ ] Automation
  - [ ] Integration
  - [ ] Runtimes
  - [ ] Any other that should be considered 

I'm around to assist, connect when you have a moment so we can move this community forward. P-)

**Comment by sabre1041** [comment]
Hey @GrooveCS !

The CoP program does already have a logo, but I will admit that it is not used everywhere.

![cop badge](https://user-images.githubusercontent.com/1191285/90318942-966a6700-def9-11ea-902a-7bedca01fbb7.png)

Would be interested in working with you and the community to ensure that our assets have it properly represented

**Comment by garethahealy** [comment]
@sabre1041 ; is it possible to get the github org logo updated to this? i.e.:
<img width="700" alt="Screenshot 2020-08-27 at 10 43 21" src="https://user-images.githubusercontent.com/8656974/91424802-2f7e7380-e852-11ea-9cc3-2052059e82bc.png">
